name: Test

on:
  push:

jobs:
  build_servo:
    name: Build Servo
    runs-on: ubuntu-22.04
    steps:
      - name: Set LIBCLANG_PATH env
        run: echo "LIBCLANG_PATH=/usr/lib/llvm-14/lib" >> $GITHUB_ENV
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Clone mdn-bcd-collector
        uses: actions/checkout@v4
        with:
          repository: openwebdocs/mdn-bcd-collector
          submodules: true
          path: collector
      # - name: Clone Servo
      #   uses: actions/checkout@v4
      #   with:
      #     repository: servo/servo
      #     path: servo
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      # - name: Install uv
      #   uses: astral-sh/setup-uv@v4
      #   with:
      #     version: "0.5.6"
      # - name: Build Servo
      #   run: |
      #     cd servo
      #     ./mach bootstrap
      #     ./mach build
      - name: Run MDN BCD Collector in background
        run: |
          cd collector
          npm ci
          nohup npm run dev &
          until curl -s http://localhost:5200/; do
            echo "Waiting for server..."
            sleep 2
          done
      # - name: Run Servo Headless
      #   run: |
      #     cd servo
      #     ./mach run http://localhost:5200/tests/ --headless --userscripts="${{ github.workspace }}/scripts/"
